### ISSUE TITLE
[Suggestion] Adding to Spigotmc website

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [DatDonathan/blocky-kingdom#1]
I suggest adding this to the spigotmc website if you want it to gain traction. 

https://www.spigotmc.org/

**Comment by JonathanDotExe** [comment]
Hi :)

Thanks for the suggestion. I actually tried to submit it a few months ago, but I was told it was need to be verified by moderators first which took very long and when I checked a few days ago my submission was gone without any message or something.
It's generally weird that it need to be verified because from what I heard only paid plugins need to be verified and mine is free. Maybe I did something wrong when submitting. I will try again soon when I get to it :)

Anyway thanks for checking my plugin out I hope you like it :D

**Comment by JonathanDotExe** [comment]
It worked now here's the link: https://www.spigotmc.org/resources/blocky-kingdom.95682/
:)
